### ISSUE TITLE
AttributeError: img_width, img_height

### ISSUE THREAD

**Issue by eleriaedmaa** [AiliAili/MultiModal#2]
Error caused by the fact that attributes `img_width `and `img_height` are used, but their values are not defined.

**Comment by AiliAili** [comment]
They are defined in the hyperparameter settings.

For example, the following two lines in bi_lstm_inception.py define the image width and height
tf.flags.DEFINE_integer('img_width', 360, 'resized image width')
tf.flags.DEFINE_integer('img_height', 360, 'resized image height')
